baseURL = "https://about.ipfs.io/"
themesDir = "themes"
theme = "hugo-story"
languageCode = "en-us"
title = "About the IPFS.io Public Gateway"
copyright = "{year}"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.124.1"

[params]
  favicon = "favicon-32x32.svg"
